### ISSUE TITLE
remove_blank_text and other options of XMLParser missing

### ISSUE THREAD

**Issue by ghost** [tiran/defusedxml#102]
The library doesn't provide a way to remove blank text.
Using the basic lxml library:

```python
from lxml import etree

PARSER = etree.XMLParser(remove_blank_text=True)
res = etree.XML(string, parser=PARSER)
```

This is the same for any option mentionned in #23.
These are important features that should be supported .

I tried to use ``XMLParser` from the original libary with the `XML()` of this one, I also tried to use `DefusedXMLParser`.
This simply doesn't seem possible.

Can you provide an example on how to access these features?
Thank you.

**Comment by tiran** [comment]
You have to construct a `XMLParser` a custom parser with `lxml.etree.XMLParser` and pass it to `defusedxml.lxml.XML`. You should at least set `resolve_entities=False`. The custom element lookup is optional.

```python
>>> import lxml.etree
>>> import defusedxml.lxml
>>>
>>> parser = lxml.etree.Parser(remove_blank_text=True, resolve_entities=False)
>>> lookup = lxml.etree.ElementDefaultClassLookup(defusedxml.lxml.RestrictedElement)
>>> parser.set_element_class_lookup(lookup)
>>> e = defusedxml.lxml.XML("<root><el/>  </root>", parser=parser)
>>> lxml.etree.tostring(e)
b'<root><el/></root>'
```

**Comment by ghost** [comment]
Hi @tiran, you said in  #33 that
> I have deprecated the defusedxml.lxml module and will remove it in a future release.

So I shouldn't be using the solution you provide, or have you changed your mind? Because I already have the deprecation warning when following your recommendation and it doesn't seem that `RestrictedElement` is available anywhere else. 
Could you please not close this issue right away considering the solution you provide is supposed to be deprecated.

**Comment by ghost** [comment]
@tiran any update on the deprecated solution?
