### ISSUE TITLE
type stubs for mypy

### ISSUE THREAD

**Issue by jbethune** [tiran/defusedxml#104]
It would be really nice to have official type stubs for this package.

**Comment by radarhere** [comment]
The owner of this package has [previously commented on this.](https://github.com/tiran/defusedxml/issues/46#issuecomment-1739800530)

> I have no plans to include type hints in this package. It's too big of a risk. The package has about 1 million downloads every day. I might inadvertently break code or CI/CD.

**Comment by solkaz** [comment]
@jbethune I have added type stubs to typeshed [here](https://github.com/python/typeshed/pull/11179)
