### ISSUE TITLE
LXML XML Schema retrieval vulnerability

### ISSUE THREAD

**Issue by Jon-Work** [tiran/defusedxml#12]
LXML has a XML Schema retrieval vulnerability that's not fixed by defusedxml.

Vulnerable calling code looks like this:

```
    with open(schema_path) as fp:
        schema = lxml.etree.XMLSchema(lxml.etree.parse(fp))
```

Where the schema file (directly or indirectly) accidentally imports a file from HTTP: 

```
<xs:import namespace="http://www.w3.org/XML/1998/namespace"
           schemaLocation="http://www.w3.org/2001/xml.xsd" />
```

Note that in my case the actual parse() call is safe because it's parsing a trusted local file, it's the XMLSchema() call that is vulnerable, because that resolves <xs:import> statements.

While the schema I'm parsing is from a local file, I discovered that my XML schema accidentally includes a schema from HTTP, so this does an insecure HTTP request to http://www.w3.org/2001/xml.xsd .  That fails if the network is down, and would also allow a malicious attacker to replace the schema and cause problems.  There are multiple levels of include between the XML Schema file I started with and the one that contains the HTTP URL, so this wasn't obvious.

Here's the corresponding LXML issue (from 2013): https://bugs.launchpad.net/lxml/+bug/1234114

The LXML people decided it was not a security issue, because it is caused by user misconfiguration - my schema files shouldn't be including schemas from HTTP.  I think it is insecure-by-default in LXML and it is very easy to accidentally make a vulnerable program.  It's not clear how a I'm supposed to notice this misconfiguration when it works fine in testing.  It's also not clear how I can stop this bug from being reintroduced by other developers working on this project, or even write a test case for this.

I was hoping there would be something like defusedxml.lxml.XMLSchema() that I could use, but that doesn't seem to exist.

Please can defusedxml at least document this vulnerability in the LXML section, and ideally provide a safe replacement for the XMLSchema() function?

**Comment by tiran** [comment]
I can no longer reproduce the XMLSchema network issue with lxml. I even downloaded lxml 4.0.0 (2017) from PyPI. lxml tries to load schema links from local files and even uses the XML catalog on my system. But there are no network calls. lxml does not use any network related syscalls like `socket`.

The problem is probably solved. In case you still have doubts, please open an issue with lxml. I'm deprecating lxml support in `defusedxml`, because I do not have resources and expertise to continue with lxml-related issues.

## `schema.py`
```
import lxml.etree
with open("schema.xsd") as fp:
    schema = lxml.etree.XMLSchema(lxml.etree.parse(fp))
```

## `schema.xsd`
```
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="http://www.w3.org/2001/xml.xsd" />
<xs:import namespace="https://example.invalid/namespace" schemaLocation="https://example.invalid/invalid.xsd" />
</xs:schema>
```

## output
```
$ strace python3 schema.py 
...
brk(0x55e238299000)                     = 0x55e238299000
read(3, "<xs:schema xmlns:xs=\"http://www."..., 8192) = 293
read(3, "", 8192)                       = 0
read(3, "", 8192)                       = 0
stat("http://www.w3.org/2001/xml.xsd", 0x7ffe189d6700) = -1 ENOENT (No such file or directory)
stat("http://www.w3.org/2001/xml.xsd", 0x7ffe189d6600) = -1 ENOENT (No such file or directory)
stat("/etc/xml/catalog", {st_mode=S_IFREG|0644, st_size=2761, ...}) = 0
openat(AT_FDCWD, "/etc/xml/catalog", O_RDONLY) = 4
lseek(4, 0, SEEK_CUR)                   = 0
read(4, "<?xml version=\"1.0\"?>\n<!DOCTYPE "..., 8192) = 2761
read(4, "", 5431)                       = 0
close(4)                                = 0
stat("/usr/share/xml/xml.xsd", {st_mode=S_IFREG|0644, st_size=8838, ...}) = 0
stat("/usr/share/xml/xml.xsd", {st_mode=S_IFREG|0644, st_size=8838, ...}) = 0
openat(AT_FDCWD, "/usr/share/xml/xml.xsd", O_RDONLY) = 4
lseek(4, 0, SEEK_CUR)                   = 0
read(4, "<?xml version='1.0'?>\n<?xml-styl"..., 8192) = 8192
brk(0x55e2382ba000)                     = 0x55e2382ba000
read(4, "sd \n      </a> \n      will not c"..., 16384) = 646
read(4, "", 15738)                      = 0
close(4)                                = 0
stat("https://example.invalid/invalid.xsd", 0x7ffe189d6700) = -1 ENOENT (No such file or directory)
stat("https://example.invalid/invalid.xsd", 0x7ffe189d6600) = -1 ENOENT (No such file or directory)
stat("https://example.invalid/invalid.xsd", 0x7ffe189d6600) = -1 ENOENT (No such file or directory)
stat("https://example.invalid/invalid.xsd", 0x7ffe189d6550) = -1 ENOENT (No such file or directory)
stat("https://example.invalid/invalid.xsd", 0x7ffe189d6550) = -1 ENOENT (No such file or directory)
stat("https://example.invalid/invalid.xsd", 0x7ffe189d6550) = -1 ENOENT (No such file or directory)
stat("https://example.invalid/invalid.xsd", 0x7ffe189d6550) = -1 ENOENT (No such file or directory)
close(3)                                = 0
rt_sigaction(SIGINT, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f10d985fb60}, {sa_handler=0x7f10d9b4dd00, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f10d985fb60}, 8) = 0
sigaltstack(NULL, {ss_sp=0x55e23813e840, ss_flags=0, ss_size=16384}) = 0
sigaltstack({ss_sp=NULL, ss_flags=SS_DISABLE, ss_size=0}, NULL) = 0
exit_group(0)                           = ?
+++ exited with 0 +++
```
