### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by ecederstrand** [tiran/defusedxml#27]
Hi @tiran 

I have some open issues and unmerged pull requests here that have had no reaction. Just wondering if I should continue to contribute fixes, or if this project has been abandoned?

**Comment by tiran** [comment]
Yes, the project is pretty much abandoned. The next versions of CPython 2.7, 3.6, and 3.7 as well as expat 2.3.0 will contain all necessary fixes.

**Comment by mscuthbert** [comment]
The Python 3.9.2 docs seem to indicate that the Python XML modules are still vulnerable to internal billion laughs and quadratic blowup checks -- is this not the case?
