### ISSUE TITLE
Importing defusedxml.ElementTree 

### ISSUE THREAD

**Issue by brunato** [tiran/defusedxml#28]
Importing defusedxml.ElementTree before xml.etree.ElementTree cause the C optimized version (_elementtree) to not load:

```python
>>> import defusedxml.ElementTree
>>> import xml.etree.ElementTree as ET
>>> ET.Element is ET._Element_Py
True
```
Viceversa works as expected:

```python
>>> import xml.etree.ElementTree as ET
>>> import defusedxml.ElementTree
>>> ET.Element is ET._Element_Py
False
```

Best,
Davide

**Comment by tiran** [comment]
This is by design. defusedxml cannot patch C code, therefore it has to disable the C extension.

**Comment by brunato** [comment]
Only to report that, despite in the code there is a restore of the original module:

https://github.com/tiran/defusedxml/blob/f2c7c35b25f80c08923be49ac1f81e9cf95bd2ae/defusedxml/ElementTree.py#L43-L49

anyway something weird happens, because `sys.modules` contains the original ElementTree module with C optimizations but the import statement returns the pure Python version:

```python
$ python
Python 3.6.6 (default, Jul 19 2018, 14:25:17) 
[GCC 8.1.1 20180712 (Red Hat 8.1.1-5)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import defusedxml.ElementTree
>>> etmod = sys.modules['xml.etree.ElementTree']
>>> etmod.Element is etmod._Element_Py
False
>>> import xml.etree.ElementTree as ET
>>> ET.Element is ET._Element_Py
True
>>> ET is etmod
False
>>> import importlib
>>> etmod is importlib.import_module('xml.etree.ElementTree')
True
>>> 
```

Thanks,
Davide
