### ISSUE TITLE
Still doesn't work with Python 3.6

### ISSUE THREAD

**Issue by AdamWill** [tiran/defusedxml#3]
https://github.com/tiran/defusedxml/commit/1d342237b560e29e8401d0a22a776b52b09e0ae2 is not sufficient to make defusedxml work properly with Python 3.6. It stops defusedxml outright choking in `_get_py3_cls`, but it doesn't *work* properly. It results in `common._generate_etree_functions()` failing, as can be seen in the 10 failed tests from the Travis run for that commit.

I naively attempted just changing the `if PY26 or PY31:` condition in `_generate_etree_functions()` to `if PY26 or PY31 or sys.version_info >= (3, 6):` , but that's not good enough either because that code really is tailored to the Python 2.6 / 3.1 implementation; it doesn't work at all for the Python 3.6 implementation. It seems like we need an entirely new approach to defusing iterparse for 3.6, but I'm not smart enough to write that. At least, not at this time in the morning...

This is a bit of a problem for us (Fedora) as Python 3.6 landed in Rawhide today, and now defusedxml won't install and can't be rebuilt (unless we ignore the fact that it's broken and disable the tests...), and several things that depend on it can't install or be rebuilt either.

**Comment by AdamWill** [comment]
also reported this to upstream Python, since the Python docs explicitly endorse the use of defusedxml: https://bugs.python.org/issue29050

**Comment by AdamWill** [comment]
https://github.com/tiran/defusedxml/pull/4 should fix this, I think.

**Comment by justuswilhelm** [comment]
This seems to break my installation of `python3-openid==3.0.10`. If there is anything I can do to help (stack traces, debugging, testing, etc.) Please let me know. 
This is what I'm seeing right now:
```
Traceback (most recent call last):
...
  File "/Users/justusperlwitz/mailops/env/lib/python3.6/site-packages/openid/consumer/consumer.py", line 196, in <module>
    from openid.consumer.discover import discover, OpenIDServiceEndpoint, \
  File "/Users/justusperlwitz/mailops/env/lib/python3.6/site-packages/openid/consumer/discover.py", line 22, in <module>
    from openid.yadis.etxrd import nsTag, XRDSError, XRD_NS_2_0
  File "/Users/justusperlwitz/mailops/env/lib/python3.6/site-packages/openid/yadis/etxrd.py", line 31, in <module>
    SafeElementTree = importSafeElementTree()
  File "/Users/justusperlwitz/mailops/env/lib/python3.6/site-packages/openid/oidutil.py", line 83, in importSafeElementTree
    return importElementTree(module_names)
  File "/Users/justusperlwitz/mailops/env/lib/python3.6/site-packages/openid/oidutil.py", line 106, in importElementTree
    ElementTree = __import__(mod_name, None, None, ['unused'])
  File "/Users/justusperlwitz/mailops/env/lib/python3.6/site-packages/defusedxml/cElementTree.py", line 16, in <module>
    from .ElementTree import DefusedXMLParser, _IterParseIterator
  File "/Users/justusperlwitz/mailops/env/lib/python3.6/site-packages/defusedxml/ElementTree.py", line 62, in <module>
    _XMLParser, _iterparse, _IterParseIterator, ParseError = _get_py3_cls()
  File "/Users/justusperlwitz/mailops/env/lib/python3.6/site-packages/defusedxml/ElementTree.py", line 56, in _get_py3_cls
    _IterParseIterator = pure_pymod._IterParseIterator
AttributeError: module 'xml.etree.ElementTree' has no attribute '_IterParseIterator'
```

**Comment by AdamWill** [comment]
@justuswilhelm try with https://github.com/tiran/defusedxml/pull/4.patch .

**Comment by justuswilhelm** [comment]
Thanks so much for the patch, I was able to fix the issue until everything is merged to upstream.

**Comment by ThomasWaldmann** [comment]
https://travis-ci.org/nsupdate-info/nsupdate.info/jobs/193934880 having same issue, can't test nsupdate.info on py36.

**Comment by tiran** [comment]
I have releases 0.5.0 yesterday.

**Comment by AdamWill** [comment]
Thanks a lot. I have sent 0.5.0 out for Fedora 24, 25 and Rawhide, and EPEL 7. I sent 0.4.1 to EPEL 6, as EL 6 is still on Python 2.6.
