### ISSUE TITLE
Use XMLParser arguments in DefusedXMLParser

### ISSUE THREAD

**Issue by zuber7** [tiran/defusedxml#33]
Hello,

How do I use other arguments of XMLParser while using DefusedXMLParser or fromstring method of defusedxml such as the following:

attribute_defaults=False, dtd_validation=False, load_dtd=False, no_network=True, ns_clean=False, recover=False, schema: XMLSchema=None, huge_tree=False, remove_blank_text=False, remove_comments=False, remove_pis=False, strip_cdata=True, collect_ids=True, compact=True.

DefusedXMLParser only uses the following:
html=0, target=None, encoding=None, forbid_dtd=False, forbid_entities=True, forbid_external=True

Thanks

**Comment by tiran** [comment]
These are options for ``lxml.etree.XMLParser``. The ``defusedxml.lxml`` module is just an example how to limit lxml with some nasty hacks like thread local storage. I have deprecated the ``defusedxml.lxml`` module and will remove it in a future release.
