### ISSUE TITLE
LXML DeprecationWarning

### ISSUE THREAD

**Issue by martinbergpetersen** [tiran/defusedxml#38]
DeprecationWarning: defusedxml.lxml is no longer supported and will be removed in a future release.

File "/usr/local/lib/python2.7/dist-packages/defusedxml/lxml.py", line 29, in <module>
    stacklevel=2,

Why was this added? Can I help fix it?

**Comment by tiran** [comment]
I'm in contact with Stefan Behnel @scoder and we are discussion better ways to address lxml. I won't remove the module until we have come up with a solution.

**Comment by distortedsignal** [comment]
@tiran I would love to help documenting this when the fix is in - let me know if you would like some help.

**Comment by mamiksik** [comment]
Hi @tiran, 
according to your [previous comment](https://github.com/tiran/defusedxml/issues/25) all vulnerabilities has been fixed in lxml underlying lib and thus defusedxml.lxml is no longer needed but then you also say: "I'm in contact with Stefan Behnel @scoder and we are discussion better ways to address lxml. I won't remove the module until we have come up with a solution." My question is, therefore, do we need to use defusedxml with lxml or not? Has or has not been the vulnerabilities fixed in libxml2 and libxslt?

Thank you in advance for taking the time to answer my questions.

Many regards,
Martin

**Comment by carlwgeorge** [comment]
@tiran If `defused.lxml` is ["no longer needed and supported"](https://github.com/tiran/defusedxml/issues/25#issuecomment-422436105), shouldn't [this table](https://github.com/tiran/defusedxml/blob/master/README.md#python-xml-libraries) be updated?  It states that lxml is vulnerable to quadratic blowup, external entity expansion (local file), and gzip bomb (partly).

**Comment by Themanwithoutaplan** [comment]
Starting with which version can lxml deemed to be safe?

**Comment by ecederstrand** [comment]
@tiran Can you clarify the status of `defused.lxml`?

**Comment by tiran** [comment]
The module is deprecated and I plan to remove it eventually. I haven't used lxml in a long time and a lot has changed since I created defusedxml.

**Comment by dfn-certling** [comment]
As far as I read it from defusedxml's lxml module and the description in lxml's FAQ, the easy part of the answer is "no, lxml cannot be deemed to be safe out of the box". Quoting from lxml's FAQ 

> **How do I use lxml safely as a web-service endpoint?**
> [...]
> To disable entity expansion, use an XML parser that is configured with the option resolve_entities=False. Then, after (or while) parsing the document, use root.iter(etree.Entity) to recursively search for entity references. If it contains any, reject the entire input document with a suitable error response. In lxml 3.x, you can also use the new DTD introspection API to apply your own restrictions on input documents.

The default parser that lxml uses is a non argument version of [lxml.etree.XMLParser](https://lxml.de/api/lxml.etree.XMLParser-class.html), which resolves entities by default, resulting in quadratic blowup as well as local entity expansion as documented in the Readme. This can be easily verified by parsing the quadratic blowup example and looking at the resulting tree.

Judging from the FAQ alone, defusedxml's module basically implements, what the FAQ states to be necessary. (Excluding the handling of compression bombs that you might have to address in other ways and that probably cannot be done generically). Whether there emerged other issues that cannot be inferred from the docs and defusedxml's module, I don't know.
