### ISSUE TITLE
custom parser in fromstring not working

### ISSUE THREAD

**Issue by xgodon** [tiran/defusedxml#41]
i have a custom parser that works in parse() but not in fromstring() : 
it seems that the fromstring function doesn't use it

```
from ssxtd.semi_structured_xml_to_dict import DictBuilder
import defusedxml.ElementTree as DET
from io import BytesIO

a = b'<animals><i>John the <b>real</b> chicken</i><i>John the <b>real</b> chicken</i></animals>\n'
parser = DET.XMLParser(target=DictBuilder())
root = DET.fromstring(a, parser)
print(type(root))

b = BytesIO('''
<animals><i>John the <b>real</b> chicken</i></animals>
'''.encode('utf-8'))

parser = DET.XMLParser(target=DictBuilder())
tree = DET.parse(b, parser)
root = tree.getroot()
print(type(root))

```
>   <class 'xml.etree.ElementTree.Element'>
>   <class 'dict'>

**Comment by tiran** [comment]
`defusedxml.ElementTree.fromstring` has no `parser` argument. The second argument `forbid_dtd`.

https://github.com/tiran/defusedxml/blob/fa6f5a51ee93e4c35e58ca7b5b2a88a6ccba3e03/defusedxml/ElementTree.py#L151-L159

You can use `fromstring` from `xml.etree.ElementTree` instead.
