### ISSUE TITLE
etree is not found in lxml 4 

### ISSUE THREAD

**Issue by oca159** [tiran/defusedxml#44]
Hi I am receiving this error:

from lxml import etree as _etree
ImportError: cannot import name 'etree'

I am using lxml 4.2.5 but according to the documentation defusedxml supports lxml > 3

**Comment by RibeiroAna** [comment]
I'm getting the same issue here. I'm using version 0.5 of defusedxml and version lxml 4. I know lxml is going to be deprecated but it should work by version 0.5 of defusedxml, right?

**Comment by Themanwithoutaplan** [comment]
The alias should work fine so you might want to check your lxml install. Which version do you have?

```
from lxml import etree as _etree
import lxml
lxml.etree.__version__
'4.4.1'
```

**Comment by tiran** [comment]
Since nobody else has reported the problem in four years and lxml support is deprecated, I'm going to close the issue.
