### ISSUE TITLE
defusedxml is incompatible with mypy

### ISSUE THREAD

**Issue by JonZeolla** [tiran/defusedxml#46]
A library stub should be contributed to [typeshed](https://github.com/python/typeshed) for `defusedxml`, especially given that this is one of the [Python project's two recommended packages](https://docs.python.org/3/library/xml.html#the-defusedxml-and-defusedexpat-packages) for parsing untrusted XML

**Comment by tiran** [comment]
That's an excellent suggestion. I suggest that you open an issue on typeshed.

I have no plans to include type hints in this package. It's too big of a risk. The package has about 1 million downloads every day. I might inadvertently break code or CI/CD.

**Comment by radarhere** [comment]
Stubs have now been contributed to typeshed - https://github.com/python/typeshed/pull/11179 / https://pypi.org/project/types-defusedxml/
