### ISSUE TITLE
Using unicode with xml.dom.minidom and defusedxml.minidom does not behave the same

### ISSUE THREAD

**Issue by romaingz** [tiran/defusedxml#52]
Hi there,

Thanks for a great lib.

I have noticed the following that I tought might be a bug:

Calling 
```python
xml.dom.minidom.parse()
```
with `unicode` behaves the same as calling it with `str` whereas
```python
defusedxml.minidom.parse()
```
does not.

This seems due to the fact that `cpython` uses `isinstance(file, StringTypes)` [source](https://github.com/python/cpython/blob/7a41638b5b183d0b9b27449d502d0a15001134ee/Lib/xml/dom/expatbuilder.py#L921)

when `defusedxml` uses `isinstance(file, str)` [source](https://github.com/tiran/defusedxml/blob/f8e3fe87aee928224378acee5761df3ca6d95dd2/defusedxml/expatbuilder.py#L83).

Should `defusedxml` align with the standard lib?

**Comment by tiran** [comment]
Is this Python 2.7? Python 3 doesn't have a unicode type and there is only one str type.

**Comment by romaingz** [comment]
Yes it is using python 2.7

**Comment by tiran** [comment]
Python 2.7 is no longer supported, sorry.
