### ISSUE TITLE
[QUESTION] Retaining XML comments during parse

### ISSUE THREAD

**Issue by lewismc** [tiran/defusedxml#67]
We would like to retain comments in an XML object. We used to do this as follows
```
import xml.etree.ElementTree as Et
self.__xml_tree = Et.parse(path, Et.XMLParser(target=Et.TreeBuilder(insert_comments=True), encoding="utf-8"))
```
Can I retain comments in my parse object with defusedxml?
Thank you

**Comment by tiran** [comment]
I don't know. If you can retain comments with standard etree module, then it should work with defusedxml, too. Please give it a try and report back.

**Comment by lewismc** [comment]
Thanks for the response @tiran 
The following defusedxml code results in the [comments being removed](https://github.com/fireant-ci/nutch/pull/84/commits/a094013fe020a47fd613099ada380e1890adccb3)
```
from defusedxml.ElementTree import parse
self.__xml_tree = parse(path)
```
I can't see a flag to toggle on or off retention of comments. We are working on some unit tests to validate this.

**Comment by tiran** [comment]
xml.etree.elementtree doesn't support it. defusedxml is just a wrapper of stdlib's xml modules.

https://docs.python.org/3/library/xml.etree.elementtree.html#module-xml.etree.ElementTree

> Note

> Not all elements of the XML input will end up as elements of the parsed tree. Currently, this module skips over any XML comments, processing instructions, and document type declarations in the input. Nevertheless, trees built using this module’s API rather than parsing from XML text can have comments and processing instructions in them; they will be included when generating XML output. A document type declaration may be accessed by passing a custom TreeBuilder instance to the XMLParser constructor.

**Comment by lewismc** [comment]
OK. Thank you very much @tiran
