### ISSUE TITLE
sax.create_parser or sax.make_parser?

### ISSUE THREAD

**Issue by brocef** [tiran/defusedxml#7]
The docs [here](https://github.com/tiran/defusedxml#defusedxmlsax) say that the sax module exports create_parser(), but it looks like it exports make_parser() [here](https://github.com/tiran/defusedxml/blob/master/defusedxml/sax.py#L48)

**Comment by tiran** [comment]
It's a bug in the documentation. make_parser is correct, https://docs.python.org/3/library/xml.sax.html#xml.sax.make_parser
