### ISSUE TITLE
[Feature request] Automatically detect imports of vulnerable xml parsers in projects

### ISSUE THREAD

**Issue by Hritik14** [tiran/defusedxml#72]
Checking for all the xml parsers listed in the readme which are vulnerable could be of some use in projects. Although, it might not be possible to detect if they are being fed the kind of data they are specifically vulnerable to but just providing with a list of files and potential risks could of great use.

**Comment by tiran** [comment]
Python 3.7.1+ and expat 2.4.0+ come with additional mitigations. The lastest `README.txt` has more details. You can check for mitigations with:

```python
import sys
import pyexpat

has_mitigations = (
    sys.version_info >= (3, 7, 1) and
    pyexpat.version_info >= (2, 4, 0)
)
```
