### ISSUE TITLE
Please add compatibility with xmlschema

### ISSUE THREAD

**Issue by abo-abo** [tiran/defusedxml#77]
[xmlschema](https://github.com/sissaschool/xmlschema) can't be loaded after `defusedxml`:

Tested on Python 3.9.2:

```
import defusedxml
defusedxml.defuse_stdlib()
# fails
import xmlschema
```

**Comment by brunato** [comment]
Hi,
i think this is not an issue of _defusedxml_ but a limitation of _xmlschema_, that doesn't understand when a monkey patched version of ElementTree is imported. 

As maintainer of _xmlschema_ i will try make it compatible with this patched version.

**Comment by brunato** [comment]
It's due to XSD 1.0 meta-schema file that contains an entity declaration:

```xml
<!ENTITY % schemaAttrs 'xmlns:hfp CDATA #IMPLIED'>
```

so when the monkey patched lib is used an exception is raised when the XSD 1.0 meta-schema is loaded.
Maybe I will modify XSD 1.0 meta-schema file, commenting out the part with entity declaration.

**Comment by tiran** [comment]
`defusedxml.defuse_stdlib()` was an experimental feature. I included it as a quick 'n dirty hack to make a large code base secure. I strongly recommend against using the function with any modern code. You should use proper method and functions from defusedxml instead.
