### ISSUE TITLE
defusedxml has no method of registering namespaces.

### ISSUE THREAD

**Issue by oar-spease** [tiran/defusedxml#79]
As the title says, there is no equivalent of https://docs.python.org/3/library/xml.etree.elementtree.html#xml.etree.ElementTree.register_namespace

The reason this is a problem is that it makes it impossible to verify XML signatures using something like signxml- namespaces are auto-renamed from their proper names to things like 'ns0' and 'ns1' and we have no way of modifying that.

A good example of this is a SAML AuthNRequest, which may start with a tag along the lines of 
`<saml2p:AuthnRequest xmlns:saml2p="urn:oasis:names:tc:SAML:2.0:protocol" AssertionConsumerServiceURL="[...]`

When parsed using defusedxml.ElementTree.parse, it will instead be
`<ns0:AuthnRequest xmlns:ns0="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:ns1="urn:oasis:names:tc:SAML:2.0:assertion" xmlns:ns2="http://www.w3.org/2000/09/xmldsig#" AssertionConsumerServiceURL="[...]`

This obviously fails to match the signature of the XML and the entire thing bombs out. LXML handles with correctly by default, and python's built-in ElementTree offers register_namespace() as seen in https://technotes.shemyak.com/posts/xml-signatures-with-python-elementtree/ which allows you to predefine the namespaces you require, but defusedxml has no equivalent that I can find.

**Comment by gsauthof** [comment]
The defusedxml protects against XML deserialization (parsing) attacks - such as billion laughs and quadratic blowup - while your issue is about _serialization_ canonicalization.

That means you should be able to do something like this:

```
import defusedxml.ElementTree
import xml.etree.ElementTree as ET

z  = defusedxml.ElementTree.fromstring(
        '<ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#" Id="placeholder"/>',
        forbid_dtd=True)
ET.register_namespace('ds', 'http://www.w3.org/2000/09/xmldsig#')
print(ET.tostring(z))
```

IOW, you can simply parse with defusedxml but serialize with standard ElementTree and you are still protected against the attacks defusedxml was designed to protect you from.

IOW, the state of the registered namespace map isn't significant for parsing.

**Comment by anush0247** [comment]
+1

**Comment by tiran** [comment]
It's on purpose. defusedxml only provides functions and classes related to loading and parsing of XML. For everything else, use the corresponding functions, classes, and constants from Python's stdlib.

See https://pypi.org/project/defusedxml/0.8.0rc1/#defusedxml

> The defusedxml modules are not drop-in replacements of their stdlib counterparts. The modules only provide functions and classes related to parsing and loading of XML. For all other features, use the classes, functions, and constants from the stdlib modules.
