### ISSUE TITLE
Want to know the estimated time of the next version update

### ISSUE THREAD

**Issue by wwwzhangshenzecn** [tiran/defusedxml#84]
The latest version of defusedxml is Mar 8, 2021. When will the next version be released? I've been using this version for over 2 years.
So, I'd like to know when the next version is updated. Thank you.

**Comment by tiran** [comment]
0.7.1 works fine with 3.10 to 3.12. There was no need to cut a new release in the last two years. The upcoming release 0.8.0 just comes with some additional test, 3.10-3.12 classifiers, and documentation improvements.

You can test 0.8.0rc1 now. I'll release 0.8.0 final in a couple of weeks.
