### ISSUE TITLE
Cannot use `xpath` and any other functionality from `lxml`

### ISSUE THREAD

**Issue by sshishov** [tiran/defusedxml#86]
I can see that `defusedxml.lxml` is deprecated. The question what we should use to gain the functionality of `xpath` for instance.

When I am trying to do the following:

```python
from defusedxml import ElementTree

et = ElementTree.fromstring("<tag>value</tag>")
et.xpath('')
```

I got an error:
```python
AttributeError: 'xml.etree.ElementTree.Element' object has no attribute 'xpath'
```

The question is how to use `lxml`'s tree functionality?

**Comment by sshishov** [comment]
@tiran could you please suggest how to use it?

**Comment by tiran** [comment]
`defusedxml.ElementTree` does not use `lxml`. It is a variant of `xml.etree.ElementTree`, which implements XPath differently, see https://docs.python.org/3/library/xml.etree.elementtree.html#xpath-support
