### ISSUE TITLE
Missing indent function

### ISSUE THREAD

**Issue by NicoHood** [tiran/defusedxml#87]
Is it possible that this is missing?
https://docs.python.org/3/library/xml.etree.elementtree.html#xml.etree.ElementTree.indent

I get the error `AttributeError: module 'defusedxml.ElementTree' has no attribute 'indent'`

**Comment by tiran** [comment]
It's on purpose. defusedxml only provides functions and classes related to loading and parsing of XML. For everything else, use the corresponding functions, classes, and constants from Python's stdlib.

See https://pypi.org/project/defusedxml/0.8.0rc1/#defusedxml

> The defusedxml modules are not drop-in replacements of their stdlib counterparts. The modules only provide functions and classes related to parsing and loading of XML. For all other features, use the classes, functions, and constants from the stdlib modules.
