### ISSUE TITLE
[Question] When can we expect to support Python 3.10?

### ISSUE THREAD

**Issue by angelarosario** [tiran/defusedxml#90]

**Comment by angelarosario** [comment]
I found https://github.com/tiran/defusedxml/pull/74

**Comment by angelarosario** [comment]
Actually, my question still stands because 0.8.0 is not yet released. Do we have any timeline on when we can expect that version to be available in pypi?

**Comment by tiran** [comment]
0.8.0rc1 is out. Unless somebody reports a bug, I'm going to release 0.8.0 in a couple of weeks.

In the mean time, please use 0.7.1. It works with all Python versions from 3.6 to 3.12. There are zero code changes in `defusedxml` package between 0.7.1 and 0.8.0 except for version bump, typos fixes, and black style change.
